In [ ]:
# import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import seaborn as sns
import plotly.express as px

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
# ignore the warning you might get from importing ensemble from sklearn
from sklearn import tree, ensemble

In [ ]:
# import the data
precipitation = pd.read_csv("precipitation.csv")
solar = pd.read_csv("solar.csv")
sun = pd.read_csv("sun.csv")
weather = pd.read_csv("weather.csv")

In [ ]:
precipitation.head()

       Date Precip in. 24-hr Snowfall in. Snowpack Depth in.
0  1/1/2017       0.01                0.2                  4
1  1/2/2017          0                  0                  4
2  1/3/2017          T                  T                  3
3  1/4/2017        0.2                0.5                  3
4  1/5/2017       0.02                0.2                2.5

In [ ]:
solar.head()

             date  value
0  7/27/2017 0:00    NaN
1  7/27/2017 0:15    NaN
2  7/27/2017 0:30    NaN
3  7/27/2017 0:45    NaN
4  7/27/2017 1:00    NaN

In [ ]:
sun.head()

         date   sunrise    sunset  elevation     azimuth
0  2017-01-01  07:28:34  16:22:27  22.506600  181.117426
1  2017-01-02  07:28:35  16:23:23  22.599328  181.003083
2  2017-01-03  07:28:32  16:24:20  22.699437  180.890026
3  2017-01-04  07:28:28  16:25:19  22.806883  180.778345
4  2017-01-05  07:28:20  16:26:20  22.921620  180.668129

In [ ]:
weather.head()

,date,temperatureMax,temperatureMin,rainTotal,rainPercent,barometerMax,barometerMin,cloudMax,cloudMin,humidityMax,humidityMin
0,2017-01-01,34.076,29.120,0.000,0.00,30.165,29.499,NaN,NaN,87.0,64.655
1,2017-01-02,40.764,14.106,0.026,0.35,30.314,30.165,NaN,NaN,85.0,79.000
2,2017-01-03,38.420,18.680,0.026,0.35,30.300,29.512,NaN,NaN,86.0,72.000
3,2017-01-04,38.219,31.376,0.259,3.47,29.512,29.118,NaN,NaN,86.0,74.000
4,2017-01-05,31.280,20.480,0.000,0.00,29.547,29.242,NaN,NaN,74.0,52.000

Convert dates to datetime objects

In [ ]:
# making precipitation's "Date" lowercase to match all datasets
precipitation.rename(columns={"Date": "date"}, inplace=True)

# convert dates to datetime objects
weather['date'] = pd.to_datetime(weather['date'])
precipitation['date'] = pd.to_datetime(precipitation['date'])
sun['date'] = pd.to_datetime(sun['date'])
solar['date'] = pd.to_datetime(solar['date'])
solar['date'] = solar['date'].dt.date

Precipatation, weather, and sun are all measured daily, but solar is measured every 15 minutes. We are going to aggregate the solar data to be a daily sum

In [ ]:
solar_daily = (
    solar
    .groupby('date', as_index=False)['value']
    .sum()
    .rename(columns={'value': 'dailyTotal'})
)

solar_daily.head()

         date  dailyTotal
0  2017-07-27      9089.0
1  2017-07-28     29376.0
2  2017-07-29     28863.0
3  2017-07-30     30777.0
4  2017-07-31     24836.0

In [ ]:
#Question 1
# 1. How do atmospheric conditions affect solar energy production?
# (cloud cover, humidity, precipitation, and barometric pressure)

In [ ]:
# 2. Which weather variable has the strongest relationship with solar energy production?

In [ ]:
# 3. How much does cloud cover reduce daily solar energy production?